spring:
  application:
    name: product-catalog-api
  datasource:
    url: 'jdbc:postgresql://localhost:5432/catalog'
    username: postgres
    password: admin
  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
